// Design philosophy: Editorial Control Room — settings explain the trust boundary before asking for configuration.

import { useState } from 'react'
import { Check, KeyRound, ShieldCheck, SlidersHorizontal } from 'lucide-react'
import StageSequence from '../components/StageSequence'

export default function Settings() {
  const [persistKey, setPersistKey] = useState(false)
  return <div className="page page-settings"><div className="source-strip"><span className="source-tape">SOURCE TAPE / TRUST BOUNDARY</span><span>LOCAL-FIRST · CREDENTIAL STATE / NOT PERSISTED · RULES V3.2</span></div><StageSequence active="fields" /><div className="page-heading"><div><span className="section-index">06 / CONNECTION & RULES</span><h1>Settings.</h1><p>Make the model fit the desk. The browser-local workflow stays the default.</p></div><div className="settings-shield"><ShieldCheck size={18} /><span>Privacy posture<br /><b>Local-first</b></span></div></div><div className="settings-grid"><section className="settings-card"><div className="card-header"><span className="section-index">AI CONNECTION</span><KeyRound size={16} /></div><label htmlFor="base-url">OpenAI-compatible base URL</label><input id="base-url" defaultValue="http://localhost:1234" /><p className="field-hint">Used only by the browser-local provider unless a hosted proxy is introduced later.</p><label htmlFor="model">Model</label><input id="model" defaultValue="qwen / local model" /><div className="setting-toggle"><button className={`toggle ${persistKey ? 'on' : ''}`} onClick={() => setPersistKey(!persistKey)} aria-pressed={persistKey}><span /></button><span><b>Persist API key locally</b><small>Off by default. Never commit or share this value.</small></span></div><button className="button button-primary"><Check size={15} /> Test connection</button></section><section className="settings-card"><div className="card-header"><span className="section-index">GENERATION RULES</span><SlidersHorizontal size={16} /></div>{[['Language', 'Egyptian Arabic / technical terms'], ['Rules version', 'v3.2 / editable system'], ['Review pass', 'Human gate required'], ['Telemetry', 'Off / local counters only']].map(([label, value]) => <div className="setting-row" key={label}><span>{label}</span><b>{value}</b></div>)}<div className="security-note"><ShieldCheck size={16} /><span><b>Trust boundary</b> Your notes and drafts remain in the browser unless you explicitly configure a remote AI endpoint.</span></div></section></div></div>
}
