// Design philosophy: Editorial Control Room — review happens in the artifact, with status and provenance always visible.

import { Check, Download, Plus, Sparkles } from 'lucide-react'
import type { GenerationStage } from '../lib/content-types'
import { shortSlotDescription } from '../lib/campaign-config'
import { getColoringGuidance, getMontageGuidance } from '../lib/production-guidance'
import { getPlatformPresets } from '../lib/platform-presets'
import type { CombinedPack, FieldSet, PackAction, PartState } from '../lib/pack-domain'

const fieldLabels: Record<keyof FieldSet, string> = { title: 'Title', promise: 'Core promise', audience: 'Audience', hook: 'Hook', story: 'Story', insight: 'Insight', proof: 'Proof', payoff: 'Payoff', cta: 'CTA' }

export default function ArtifactEditor({ pack, part, activeStage, running, textDirection, onAction, onGenerate, onExport }: { pack: CombinedPack; part: PartState; activeStage: GenerationStage; running: boolean; textDirection: 'auto' | 'ltr' | 'rtl'; onAction: (action: PackAction) => void; onGenerate: () => void; onExport: () => void }) {
  const hasArtifacts = Boolean(part.fields || part.script || part.montage || part.grade)
  const stageCopy: Record<GenerationStage, { title: string; description: string; prerequisite?: string }> = {
    fields: { title: 'Shape the brief.', description: 'Turn the topic into an editable set of claims, audience cues, proof, and payoff.' },
    script: { title: 'Draft the story.', description: 'Build a recordable narrative from the reviewed fields.', prerequisite: 'Fields must be shaped before the script can run.' },
    montage: { title: 'Plan the cut.', description: 'Translate the script into a timecoded, recordable shot plan.', prerequisite: 'A script must exist before the montage can run.' },
    grade: { title: 'Set the look.', description: 'Create a restrained visual recipe that protects technical legibility.', prerequisite: 'A script must exist before the grade can run.' },
  }
  const currentStage = stageCopy[activeStage]
  const shortSlot = part.key === 'long' ? null : shortSlotDescription(Number(part.key.replace('short-', '')), pack.campaign)
  const montageGuidance = getMontageGuidance(pack.campaign.montageTool)
  const coloringGuidance = getColoringGuidance(pack.campaign.coloringTool)
  const platformPresets = getPlatformPresets(pack.campaign.platforms)
  const blocked = (activeStage === 'script' && !part.fields) || ((activeStage === 'montage' || activeStage === 'grade') && !part.script)

  return <div className="preview-panel">
    <div className="preview-toolbar"><span className="section-index">03 / EDITOR</span><span className="source-tape">{part.label} / {shortSlot?.label || 'Main video'} / {part.stageStatus[activeStage].toUpperCase()}</span></div>
    {part.error ? <div className="error-preview"><span className="empty-tape">STAGE ERROR / RECOVERABLE</span><h2>{part.error}</h2><p>Check the local provider connection or adjust the model settings, then retry only this part.</p><button className="button button-quiet" onClick={onGenerate} disabled={running}><Sparkles size={15} /> Retry this part</button></div> : hasArtifacts ? <div className="preview-content">
      <div className="preview-badge"><Check size={14} /> {part.label} / {shortSlot?.label || 'Main video'} / {part.stageStatus[activeStage]}</div>
      <h2>{part.fields?.title || pack.meta.topic || 'Your next technical story'}</h2>
      {part.warnings?.length ? <div className="warning-panel"><span className="empty-tape">REVIEW NOTES / {part.warnings.length}</span>{part.warnings.map((warning) => <p key={warning}>{warning}</p>)}</div> : null}
      {part.fields && <div className="field-review-grid">{(Object.keys(fieldLabels) as Array<keyof FieldSet>).map((key) => <label key={key}><span>{fieldLabels[key]}</span><textarea dir={textDirection} aria-label={fieldLabels[key]} rows={key === 'title' || key === 'audience' || key === 'cta' ? 2 : 3} value={part.fields?.[key] || ''} onChange={(event) => onAction({ type: 'update-field', partKey: part.key, field: key, value: event.target.value })} placeholder={`Add ${fieldLabels[key].toLowerCase()}…`} /></label>)}</div>}
      {part.script && <label className="artifact-editor-block"><span className="section-index">SCRIPT / EDITABLE MARKDOWN</span><textarea dir={textDirection} aria-label="Editable script markdown" className="script-editor" value={part.script.markdown} onChange={(event) => onAction({ type: 'update-script', partKey: part.key, markdown: event.target.value })} rows={13} /></label>}
      {activeStage === 'script' && <div className="platform-guide-card"><span className="section-index">PLATFORM ADAPTATION / {platformPresets.length} SELECTED</span>{platformPresets.map((preset) => <article key={preset.id}><strong>{preset.label}</strong><small>{preset.aspectRatio} · {preset.role}</small><p>{preset.ctaGuidance}</p></article>)}</div>}
      {activeStage === 'montage' && <div className="production-guide-card"><span className="section-index">SIMPLE MONTAGE / {montageGuidance.toolLabel.toUpperCase()} · {montageGuidance.version}</span><p>{montageGuidance.summary}</p><ol>{montageGuidance.steps.map((step) => <li key={step}>{step}</li>)}</ol><small><b>Keep it simple:</b> {montageGuidance.avoid}</small><small><b>Review:</b> {montageGuidance.reviewCue}</small></div>}
      {activeStage === 'grade' && <div className="production-guide-card"><span className="section-index">SIMPLE COLORING / {coloringGuidance.toolLabel.toUpperCase()} · {coloringGuidance.version}</span><p>{coloringGuidance.summary}</p><ol>{coloringGuidance.steps.map((step) => <li key={step}>{step}</li>)}</ol><small><b>Keep it simple:</b> {coloringGuidance.avoid}</small><small><b>Review:</b> {coloringGuidance.reviewCue}</small></div>}
      {part.montage && <div className="artifact-editor-block"><span className="section-index">MONTAGE / SHOT TABLE</span><div className="montage-editor">{part.montage.map((shot, index) => <div className="montage-editor-row" key={`${shot.tStart}-${index}`}><input aria-label="Start timecode" value={shot.tStart} onChange={(event) => onAction({ type: 'update-montage', partKey: part.key, index, shot: { tStart: event.target.value } })} /><input aria-label="End timecode" value={shot.tEnd} onChange={(event) => onAction({ type: 'update-montage', partKey: part.key, index, shot: { tEnd: event.target.value } })} /><input aria-label="Shot type" value={shot.shot} onChange={(event) => onAction({ type: 'update-montage', partKey: part.key, index, shot: { shot: event.target.value } })} /><input aria-label="On-screen direction" value={shot.onScreen} onChange={(event) => onAction({ type: 'update-montage', partKey: part.key, index, shot: { onScreen: event.target.value } })} /></div>)}</div></div>}
      {part.grade && <div className="artifact-editor-block"><span className="section-index">GRADE / GLOBAL RECIPE</span><div className="grade-editor"><label>Filter<input value={part.grade.filter} onChange={(event) => onAction({ type: 'update-grade', partKey: part.key, grade: { filter: event.target.value } })} /></label><label>Intensity<input type="number" min="0" max="100" value={part.grade.intensity} onChange={(event) => onAction({ type: 'update-grade', partKey: part.key, grade: { intensity: Number(event.target.value) } })} /></label><label>Contrast<input type="number" min="-100" max="100" value={part.grade.contrast} onChange={(event) => onAction({ type: 'update-grade', partKey: part.key, grade: { contrast: Number(event.target.value) } })} /></label><label>Notes<textarea rows={3} value={part.grade.notes} onChange={(event) => onAction({ type: 'update-grade', partKey: part.key, grade: { notes: event.target.value } })} /></label></div></div>}
      <div className="artifact-editor-block"><span className="section-index">RUN-SHEET / HAND-OFF</span><div className="runsheet-editor">{pack.runSheet.map((item, index) => <label key={item.label}><input type="checkbox" checked={item.done} onChange={() => onAction({ type: 'toggle-run-sheet', index })} /> <span>{item.label}</span></label>)}</div></div>
      <div className="preview-actions"><button className="button button-quiet" onClick={onGenerate} disabled={running}><Sparkles size={15} /> {part.stageStatus[activeStage] === 'done' ? 'Regenerate part' : 'Generate stage'}</button><button className="button button-quiet" onClick={onExport}><Download size={15} /> Export .md</button></div>
    </div> : <div className="empty-preview"><div className="empty-mark"><Plus size={20} /></div><span className="empty-tape">{activeStage.toUpperCase()} / WAITING</span><h2>{currentStage.title}</h2><p>{blocked ? currentStage.prerequisite : currentStage.description}</p>{!blocked && <button className="button button-primary" onClick={onGenerate} disabled={running}><Sparkles size={15} /> {running ? 'Working…' : `Generate ${activeStage}`}</button>}<span className="empty-rule" /></div>}
  </div>
}
